# LLVM toolchain for x86-64 macOS (native).

set(CMAKE_OSX_ARCHITECTURES x86_64)
set(LLVM_ENABLE_SUPPORT_XCODE_SIGNPOSTS FORCE_OFF CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/initial-cache.cmake")
