name: Build FlatBuffers wheels

on:
  push:
    branches: [main]
    paths:
      - packages/flatbuffers/**
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-dependency.yml
    with:
      package: packages/flatbuffers
    permissions:
      contents: write
      pages: write
      id-token: write
